### ISSUE TITLE
NFC don't work

### ISSUE THREAD

**Issue by anomalchik** [KudProject/device_asus_X00T#1]
[Try this](https://gist.github.com/anomalchik/c6f75b539c697dfe8c3c81d1504295b4)

**Comment by krasCGQ** [comment]
```
...
patching file rootdir/etc/init.qcom.rc                                          
patch unexpectedly ends in middle of line                                       
Hunk #1 merged at 430-431.
```

Normal?

**Comment by anomalchik** [comment]
maybe, patch created under win)

**Comment by krasCGQ** [comment]
Pushed to `staging/lineage-16.0` as commit 4473f08cbe880c0e8777919e73eeed4296d546c6, because I need to use external server for building real quick (current server can't even handle a single build in less than 24 hours).

**Comment by anomalchik** [comment]
OMG. So slowly?

**Comment by ironmerc** [comment]
> [Try this](https://gist.github.com/anomalchik/c6f75b539c697dfe8c3c81d1504295b4)

Have u checked if it works ?

**Comment by krasCGQ** [comment]
@anomalchik yep, blame Contabo for that slowness.

**Comment by anomalchik** [comment]
> > [Try this](https://gist.github.com/anomalchik/c6f75b539c697dfe8c3c81d1504295b4)
> 
> Have u checked if it works ?

@alex24msk-4PDA has been using my configs for a long time.
I don't have opportunity to build roms.

**Comment by ironmerc** [comment]
> > > [Try this](https://gist.github.com/anomalchik/c6f75b539c697dfe8c3c81d1504295b4)
> > 
> > 
> > Have u checked if it works ?
> 
> @alex24msk-4PDA has been using my configs for a long time.
> I don't have opportunity to build roms.

Ohk , Let's see if this fixes NFC

**Comment by alex-msk-dev** [comment]
I have long already threw everything you need in chat India, no one used anything. Why be surprised

**Comment by akshatsinha2002** [comment]
@alex24msk-4PDA Lol

**Comment by alex-msk-dev** [comment]
NFC full work

**Comment by alex-msk-dev** [comment]
http://4pda.ru/forum/index.php?act=findpost&pid=76079358&anchor=Spoil-76079358-6

**Comment by ironmerc** [comment]
> NFC full work

Ok

**Comment by alex-msk-dev** [comment]
> @anomalchik yep, blame Contabo for that slowness.

You plan builds off Los16 ?

**Comment by anomalchik** [comment]
@krasCGQ also may to need move nfc firmware into vendor/lib

**Comment by krasCGQ** [comment]
@alex24msk-4PDA XenonHD.

**Comment by anomalchik** [comment]
> @krasCGQ also may to need move nfc firmware into vendor/lib

from vendor/firmware

**Comment by krasCGQ** [comment]
[XenonHD-181118-Experimental-X00T.zip](https://mirrors.c0urier.net/android/teamhorizon/P/Experimental/X00T/XenonHD-181118-Experimental-X00T.zip)

This includes the said NFC fix, but not moving the NFC libs from `/vendor/firmware` to `/vendor/lib`.

**Comment by anomalchik** [comment]
yep. New nfc service search *.so fw in vendor/lib/. 
If nfc firmware have *.fw format then into vendor/firmware.

**Comment by anomalchik** [comment]
[Propietary list patch](https://gist.github.com/anomalchik/17626099a416e7a3ed9a17a6f6ad529c)
unfortunately I don't have opportunity for download vendor repo and make changes for this.

**Comment by ironmerc** [comment]
> [Propietary list patch](https://gist.github.com/anomalchik/17626099a416e7a3ed9a17a6f6ad529c)
> unfortunately I don't have opportunity for download vendor repo and make changes for this.

https://github.com/akshatsinha2002/proprietary_vendor_asus/commit/d062573bdd031ac7841f3a18fb569fd1eeefd3db

**Comment by anomalchik** [comment]
thanks)

**Comment by akshatsinha2002** [comment]
@akshatsinha2002 @krasCGQ ^

**Comment by anomalchik** [comment]
> > [Propietary list patch](https://gist.github.com/anomalchik/17626099a416e7a3ed9a17a6f6ad529c)
> > unfortunately I don't have opportunity for download vendor repo and make changes for this.
> 
> [akshatsinha2002/proprietary_vendor_asus@d062573](https://github.com/akshatsinha2002/proprietary_vendor_asus/commit/d062573bdd031ac7841f3a18fb569fd1eeefd3db)

you have derp ))
vendor/asus/X00T/proprietary/vendor/**firmware**/libpn553_fw.so:$(TARGET_COPY_OUT_VENDOR)/lib/libpn553_fw.so \

**Comment by anomalchik** [comment]
[Vendor patch](https://gist.github.com/anomalchik/da6eddccb40364933494261f48bdabb1)

**Comment by ironmerc** [comment]
@anomalchik Force pushed https://github.com/akshatsinha2002/proprietary_vendor_asus/commit/75bbe45a0fb7d9f22ec32ff544484f4185e8c978

**Comment by anomalchik** [comment]
@krasCGQ You can also remove unused panels from kernel dtb
https://github.com/freemarkw/android_kernel_asus_sdm660/blob/caf-7.2/arch/arm/boot/dts/qcom/X00TD/X00TD-panels.dtsi#L19
